### PR TITLE
Portuguese translation

### PR DESCRIPTION
**Pull request by ciceromsjr**
I have translated the resources to Portuguese.

In addition, I created an IconView widget class which extends from ImageView and provides a method called "setIcon(Icon icon)".
In the future, we could create the icon options by attributeset and show to the user an icon related to a stored icon id.

### CODE REVIEW

**Comment by maltaisn** [comment]
Thank you for your contribution! I originally merged the pull request but reverted back, I think there are a few things that needs to be improved with labels, here's a few tips:

**1. Try to keep only the meaning of one label, for example:**
```xml
<label name="boulevard">
    <alias>Estrada</alias>
    <alias>Rodovia</alias>
    <alias>Rua</alias>
    <alias>Avenida</alias>
</label>
```
I don't know Portuguese but after searching a little it seems that "boulevard" has no equivalent except maybe "avenida" which looks like "avenue". So instead of having a lot of different words with similar definitions with none that matches exactly, you have two choices:
- Use only one, like `<label name="boulevard">@label/avenue</label>` to make a reference to `avenue` label which already exists.
- Leave a blank value, `<label name="boulevard">_</label>`. Why `_`? Because you cannot use self-closing tag and an empty body shows a warning so use an underscore which will get normalized to an empty value, i.e, no label.

What happens now is that there are a lot of duplicated labels. If we take icon 355 that has the following labels: `road,avenue,boulevard,highway,street,pathway`. After adding aliases, it will result in the following list: `rua,avenida,estrada,rodovia,rua,avenida,rodovia,rua,rua`. As you can see, a bunch of labels are duplicated.

There are a lot of examples of this: barrel (only keep "barril"), boat (only keep "barco"), brightness (only keep "brilho"), crane (only keep "guindaste"), etc. 

Keep in mind that labels must represent a single word with closely related synonyms, alternate meanings of icons are defined in `icons.xml` with additional labels.

The performance and memory usage impact is not very high and duplicates could probably be deleted when labels are loaded, but this is bad style. The reason of this is mostly to have conformity across different translations. 

**2. Anglicisms**

When translating labels, try to avoid anglicism except if they are really part of the language and if they are really used. For example:
```xml
<label name="headphones">
    <alias>Headphones</alias>
    <alias>Headset</alias>
    <alias>Earphones</alias>
    <alias>Earbuds</alias>
    <alias>Fone</alias>
</label>
```
4 words are from English, although the use of the English words on the [Wikipedia article](https://pt.wikipedia.org/wiki/Auscultadores) shows that you're probably right. I'll let you judge of this by yourself.

**3. Normalization**
As you may know already, label values are normalized as well as the search request to provide more results. All special characters except letters and numbers are removed, all diacritics too, hyphens, apostrophes, etc.
```xml
<label name="hard_disk">
    <alias>HD</alias>
    <alias>Dísco rígido</alias>
    <alias>Disco rigido</alias>
</label>
```
Here it may just be a mistake, but there's no need to duplicate `Disco rigido` for two different uses of accents.

**4. Label references**
Not a necessity, but for good style. If two label values are the same and they are related, one can make a reference to the other, see the [References](https://github.com/maltaisn/icondialoglib/wiki/Translating#references) wiki page section for more information.

Here's the complete list of identical label values: (the number after `$` is the alias index)
```
creation/magic
chat$2/letter$2/message
cold/winter$1
football/soccer$0
grease_pen/pen
electric_guitar$1/guitar
printer/schredder
boulevard$0/road
font/source
computer/laptop$2
mobile$0/phone$1
pie/pizza
bicycle$2/cycling
electrical_plug/electrical_socket$0
boulevard$2/pathway/street
anvil/blacksmith
future/history
electronic_chip$1/electronic_circuit
disk$0/pipe
console$1/terminal
folder/past
cinema/film$1
candy/candycane$1
call/phone$0
chat$1/talking
gun/weapon
hear/stethoscope
insurance$1/security
laptop$1/notebook
animal/pet$1
bowl$0/owl
dice$1/game$1
wall$1/wand
bookmark/highlighter
hour/time$1
buggy/cart/grocery$0
egg_cell$1/spermatozoid
chess_rook/tower
desk/table
gavel/hammer
camcorder$1/video
firework$2/rocket
human/person$0
home$0/house
pasta$0/weight$1
film$0/movie
pick/summit
hot/hot_tub$2
piggy_bank$0/savings$2
oar/rowing
livestock$0/pig
piggy_bank$3/savings$0
dumbbell$0/heavy$0/weight$0
cake/muffin
fence/gate$1
bulletin_board$2/frame
building$2/church
bomb/pump
down/low
boombox$1/sound
crosshairs$1/location
broom/housework
equality/math_equal
graffiti/spray
crosshairs$0/gps
stopwatch/timer$1
image$1/photo
fill/paint
piggy_bank$1/savings$3
grade/grid
ceiling$2/lightning
bath/hot_tub$1
avenue/boulevard$3
cannabis$1/drug
decision/direction
beaker/stove$1
brightness$2/moon/programming_lua
chess_knight/horse
ball/bauble
bulletin_board$1/pin
egg_cell$0/reproduction
dial/keyboard
category/tag$1
camcorder$0/camera
language/tongue
signal/traffic_light$1
bow_tie/tie
chili_food/pepper
boulevard$1/highway
barrel$1/oil
mobile$1/phone$2
ceiling$0/lamp/lightbulb
question$2/question_mark
broken$0/heart
gauge/speedometer
crop/cut
building$3/construction
cash/money
tortoise/turtle
repeat$1/update
click/sound_ring/touch_screen
crane$1/dock$0
cookie/dessert$0
fuel/gas$2
boombox$0/radio
darts/data/dice$0
checkerboard$1/chess
email/letter$1
boat$1/navigation
greek_letter/pi
piggy_bank$2/savings$1
glass/glass_flute
cactus/desert
floppy_disk$1/save
coin/currency
snow/weather_snowy
```
Generated from my script `analyse_xml.py`, documented [here](https://github.com/maltaisn/icondialoglib/wiki/Validating-XML#translating). That list could also help you with point 1.

Point 1 is definitively the most important and needs to be fixed before merging the pull-request, the rest can wait. Please make another pull request if you do it, I screwed up with git when reverting back.

As for the IconView, I don't know if I understand. Is it so users can use icons like how `android:src` is used to put a drawable on an ImageView, so they can avoid defining drawables that are already defined by the library? If so, an attribute needs to be added for XML, I feel like the advantage is minimal if icon can only be set by code.

This was one hell of a long comment, sorry. Apart from this, I wanted to thank you for your time, translating this library certainly isn't an easy task. I really appreciate your contribution, these are just tips for making it better. Don't take it personal, I just want to have conformity across translations and provide a better user experience.

**Comment by ciceromsjr** [comment]
Thank you for commenting on my pull request.

About the point 1, I thought I had to create related words to the icon itself, to make it easier to the user to find the desired icon. I will normalize it since I understood the objective of it.

Point 2, yes, we have these words in Portuguese as well, but I will remove ```Earphones``` and ```Earbuds``` because we don't have these ones.

Point 3, I did not know that the library worked like that and I will normalize it too.

About the point 4, I will change it as well. It totally makes sense.

For IconView, I thought it could be a widget like ```MaterialIconView``` from https://github.com/code-mc/material-icon-lib. It is pretty useful and would be awesome if your library provides such feature. If you think so, we could go ahead with it.

Finally, congrats for this library, it is amazing.

**Comment by hieudev** [comment]
I'm translating into spanish. Give me some days.
Do you have  a screenshot with ALL the images? It'd help a lot.

**Comment by maltaisn** [comment]
I don't, but I could make some if you need. Do you only need a screenshot with the icon itself or do you need more information like the ID or the labels that go with it?

**Comment by hieudev** [comment]
It's faster assigning a translation from an image than from a word. The
word may drive into an translation error and it's needed to search on
internet for context. With and image it is straightfull.

If you can quickly make a screenshot with all images ordered alphabetically
as the xml list, please do it. If you can't, don't worry.

**Comment by maltaisn** [comment]
The XML list ordered alphabetically is actually the list of labels, not the icon names. Icons don't have a name, instead they have multiple labels. I will make you an image with the complete list of labels and a few icons that use the label next to it, it will be more convenient.

**Comment by maltaisn** [comment]
I made a script to generate the images: https://github.com/maltaisn/icondialoglib/blob/master/icondialog/icons/labels_image.kts, you can download the output here: [label-images.zip](https://github.com/maltaisn/icondialoglib/files/2957686/label-images.zip).

The images look like this, and there's one for each label.
alarm

**Comment by hieudev** [comment]
nice!

**Pull request merged**
